version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: store_managing_system
    restart: unless-stopped
    ports:
      - "13307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bucket
      MYSQL_USER: bucket
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: